// filmData.js - Centralized film database
export const filmsDatabase = [
  // Hindi Films
  { 
    id: 1, 
    title: "Dangal", 
    language: "Hindi", 
    genre: ["Sports", "Drama", "Biography"], 
    tone: "Uplifting", 
    theme: ["Family", "Determination"], 
    maturity: "U", 
    mood: "Inspirational Sports Drama", 
    year: 2016, 
    rating: 8.4,
    director: "Nitesh Tiwari"
  },
  { 
    id: 2, 
    title: "Andhadhun", 
    language: "Hindi", 
    genre: ["Thriller", "Comedy"], 
    tone: "Dark", 
    theme: ["Deception", "Morality"], 
    maturity: "A", 
    mood: "Dark Comedy Thriller", 
    year: 2018, 
    rating: 8.2,
    director: "Sriram Raghavan"
  },
  { 
    id: 3, 
    title: "Queen", 
    language: "Hindi", 
    genre: ["Comedy", "Drama"], 
    tone: "Uplifting", 
    theme: ["Self-Discovery", "Independence"], 
    maturity: "U/A", 
    mood: "Uplifting Self-Discovery Comedy", 
    year: 2013, 
    rating: 8.2,
    director: "Vikas Bahl"
  },
  { 
    id: 4, 
    title: "Article 15", 
    language: "Hindi", 
    genre: ["Crime", "Drama"], 
    tone: "Serious", 
    theme: ["Social Justice", "Caste System"], 
    maturity: "A", 
    mood: "Serious Social Drama", 
    year: 2019, 
    rating: 8.1,
    director: "Anubhav Sinha"
  },
  { 
    id: 5, 
    title: "Gully Boy", 
    language: "Hindi", 
    genre: ["Drama", "Music"], 
    tone: "Inspirational", 
    theme: ["Dreams", "Social Class"], 
    maturity: "U/A", 
    mood: "Inspirational Musical Drama", 
    year: 2019, 
    rating: 7.9,
    director: "Zoya Akhtar"
  },

  // Marathi Films
  { 
    id: 6, 
    title: "Sairat", 
    language: "Marathi", 
    genre: ["Romance", "Drama"], 
    tone: "Intense", 
    theme: ["Love", "Caste", "Honor Killing"], 
    maturity: "A", 
    mood: "Intense Romance Drama", 
    year: 2016, 
    rating: 8.3,
    director: "Nagraj Manjule"
  },
  { 
    id: 7, 
    title: "Court", 
    language: "Marathi", 
    genre: ["Drama"], 
    tone: "Realistic", 
    theme: ["Justice System", "Social Commentary"], 
    maturity: "U/A", 
    mood: "Realistic Legal Drama", 
    year: 2014, 
    rating: 8.1,
    director: "Chaitanya Tamhane"
  },
  { 
    id: 8, 
    title: "Natsamrat", 
    language: "Marathi", 
    genre: ["Drama"], 
    tone: "Tragic", 
    theme: ["Family", "Aging", "Respect"], 
    maturity: "U/A", 
    mood: "Tragic Family Drama", 
    year: 2016, 
    rating: 8.7,
    director: "Mahesh Manjrekar"
  },

  // Tamil Films
  { 
    id: 9, 
    title: "Vikram Vedha", 
    language: "Tamil", 
    genre: ["Action", "Thriller"], 
    tone: "Gritty", 
    theme: ["Good vs Evil", "Morality"], 
    maturity: "A", 
    mood: "Gritty Crime Thriller", 
    year: 2017, 
    rating: 8.4,
    director: "Pushkar-Gayathri"
  },
  { 
    id: 10, 
    title: "96", 
    language: "Tamil", 
    genre: ["Romance", "Drama"], 
    tone: "Nostalgic", 
    theme: ["Love", "Memory", "Time"], 
    maturity: "U/A", 
    mood: "Nostalgic Romance Drama", 
    year: 2018, 
    rating: 8.5,
    director: "C. Prem Kumar"
  },
  { 
    id: 11, 
    title: "Asuran", 
    language: "Tamil", 
    genre: ["Action", "Drama"], 
    tone: "Intense", 
    theme: ["Caste Violence", "Family"], 
    maturity: "A", 
    mood: "Intense Rural Drama", 
    year: 2019, 
    rating: 8.4,
    director: "Vetrimaaran"
  },

  // Telugu Films
  { 
    id: 12, 
    title: "Arjun Reddy", 
    language: "Telugu", 
    genre: ["Romance", "Drama"], 
    tone: "Intense", 
    theme: ["Love", "Self-Destruction"], 
    maturity: "A", 
    mood: "Intense Romance Drama", 
    year: 2017, 
    rating: 8.1,
    director: "Sandeep Reddy Vanga"
  },
  { 
    id: 13, 
    title: "Mahanati", 
    language: "Telugu", 
    genre: ["Biography", "Drama"], 
    tone: "Nostalgic", 
    theme: ["Cinema", "Life of Actor"], 
    maturity: "U", 
    mood: "Nostalgic Biographical Drama", 
    year: 2018, 
    rating: 8.6,
    director: "Nag Ashwin"
  },
  { 
    id: 14, 
    title: "Jersey", 
    language: "Telugu", 
    genre: ["Sports", "Drama"], 
    tone: "Emotional", 
    theme: ["Cricket", "Second Chances", "Family"], 
    maturity: "U/A", 
    mood: "Emotional Sports Drama", 
    year: 2019, 
    rating: 8.6,
    director: "Gowtam Tinnanuri"
  },
  { 
    id: 15, 
    title: "C/o Kancharapalem", 
    language: "Telugu", 
    genre: ["Romance", "Drama"], 
    tone: "Realistic", 
    theme: ["Love Across Ages", "Small Town"], 
    maturity: "U/A", 
    mood: "Realistic Multi-generational Romance", 
    year: 2018, 
    rating: 8.4,
    director: "Venkatesh Maha"
  },
   { id: 16, title: "Dangal", language: "Hindi", genre: ["Sports", "Drama", "Biography"], tone: "Uplifting", theme: ["Family", "Determination"], maturity: "U", mood: "Inspirational Sports Drama", year: 2016, rating: 8.4 },
    { id: 2, title: "Tumhari Sulu", language: "Hindi", genre: ["Comedy", "Drama"], tone: "Heartwarming", theme: ["Family", "Women Empowerment"], maturity: "U", mood: "Feel-Good Family Comedy", year: 2017, rating: 7.1 },
    { id: 3, title: "Andhadhun", language: "Hindi", genre: ["Thriller", "Comedy"], tone: "Dark", theme: ["Deception", "Morality"], maturity: "A", mood: "Dark Comedy Thriller", year: 2018, rating: 8.2 },
    { id: 4, title: "Article 15", language: "Hindi", genre: ["Crime", "Drama"], tone: "Serious", theme: ["Social Justice", "Caste System"], maturity: "A", mood: "Serious Social Drama", year: 2019, rating: 8.1 },
    { id: 5, title: "Zindagi Na Milegi Dobara", language: "Hindi", genre: ["Adventure", "Comedy", "Drama"], tone: "Uplifting", theme: ["Friendship", "Adventure"], maturity: "U/A", mood: "Adventure Buddy Comedy", year: 2011, rating: 8.2 },
    { id: 6, title: "Pink", language: "Hindi", genre: ["Drama", "Thriller"], tone: "Intense", theme: ["Women's Rights", "Justice"], maturity: "A", mood: "Intense Social Thriller", year: 2016, rating: 8.1 },
    { id: 7, title: "Queen", language: "Hindi", genre: ["Comedy", "Drama"], tone: "Uplifting", theme: ["Self-Discovery", "Independence"], maturity: "U/A", mood: "Uplifting Self-Discovery Comedy", year: 2013, rating: 8.2 },
    { id: 8, title: "Gully Boy", language: "Hindi", genre: ["Drama", "Music"], tone: "Inspirational", theme: ["Dreams", "Social Class"], maturity: "U/A", mood: "Inspirational Musical Drama", year: 2019, rating: 7.9 },
    { id: 9, title: "Stree", language: "Hindi", genre: ["Horror", "Comedy"], tone: "Humorous", theme: ["Folklore", "Gender Roles"], maturity: "U/A", mood: "Horror Comedy", year: 2018, rating: 7.5 },
    { id: 10, title: "Badhaai Ho", language: "Hindi", genre: ["Comedy", "Drama"], tone: "Heartwarming", theme: ["Family", "Unconventional"], maturity: "U/A", mood: "Heartwarming Family Comedy", year: 2018, rating: 7.9 },
    { id: 11, title: "Piku", language: "Hindi", genre: ["Comedy", "Drama"], tone: "Slice of Life", theme: ["Family", "Relationships"], maturity: "U/A", mood: "Slice of Life Family Drama", year: 2015, rating: 7.6 },
    { id: 12, title: "Newton", language: "Hindi", genre: ["Comedy", "Drama"], tone: "Satirical", theme: ["Democracy", "Bureaucracy"], maturity: "U/A", mood: "Political Satire", year: 2017, rating: 7.8 },
    { id: 13, title: "Masaan", language: "Hindi", genre: ["Drama"], tone: "Melancholic", theme: ["Life", "Death", "Social Issues"], maturity: "A", mood: "Melancholic Social Drama", year: 2015, rating: 8.1 },

    // Marathi Films
    { id: 14, title: "Sairat", language: "Marathi", genre: ["Romance", "Drama"], tone: "Intense", theme: ["Love", "Caste", "Honor Killing"], maturity: "A", mood: "Intense Romance Drama", year: 2016, rating: 8.3 },
    { id: 15, title: "Court", language: "Marathi", genre: ["Drama"], tone: "Realistic", theme: ["Justice System", "Social Commentary"], maturity: "U/A", mood: "Realistic Legal Drama", year: 2014, rating: 8.1 },
    { id: 16, title: "Natsamrat", language: "Marathi", genre: ["Drama"], tone: "Tragic", theme: ["Family", "Aging", "Respect"], maturity: "U/A", mood: "Tragic Family Drama", year: 2016, rating: 8.7 },
    { id: 17, title: "Fandry", language: "Marathi", genre: ["Drama"], tone: "Raw", theme: ["Caste", "First Love", "Social Hierarchy"], maturity: "U/A", mood: "Raw Social Drama", year: 2013, rating: 8.0 },
    { id: 18, title: "Katyar Kaljat Ghusali", language: "Marathi", genre: ["Musical", "Drama"], tone: "Passionate", theme: ["Music", "Rivalry", "Art"], maturity: "U", mood: "Passionate Musical Drama", year: 2015, rating: 8.4 },
    { id: 19, title: "Yellow", language: "Marathi", genre: ["Drama"], tone: "Emotional", theme: ["Mental Health", "Relationships"], maturity: "U/A", mood: "Emotional Psychological Drama", year: 2014, rating: 7.6 },
    { id: 20, title: "Timepass", language: "Marathi", genre: ["Romance", "Comedy"], tone: "Light", theme: ["Young Love", "College Life"], maturity: "U", mood: "Light Romantic Comedy", year: 2014, rating: 7.8 },
    { id: 21, title: "Duniyadari", language: "Marathi", genre: ["Drama", "Romance"], tone: "Nostalgic", theme: ["Friendship", "Love", "College Life"], maturity: "U", mood: "Nostalgic College Drama", year: 2013, rating: 8.2 },
    { id: 22, title: "Killa", language: "Marathi", genre: ["Drama"], tone: "Gentle", theme: ["Childhood", "Moving", "Adaptation"], maturity: "U", mood: "Gentle Coming-of-Age Drama", year: 2014, rating: 7.8 },

    // Tamil Films
    { id: 23, title: "Vikram Vedha", language: "Tamil", genre: ["Action", "Thriller"], tone: "Gritty", theme: ["Good vs Evil", "Morality"], maturity: "A", mood: "Gritty Crime Thriller", year: 2017, rating: 8.4 },
    { id: 24, title: "96", language: "Tamil", genre: ["Romance", "Drama"], tone: "Nostalgic", theme: ["Love", "Memory", "Time"], maturity: "U/A", mood: "Nostalgic Romance Drama", year: 2018, rating: 8.5 },
    { id: 25, title: "Asuran", language: "Tamil", genre: ["Action", "Drama"], tone: "Intense", theme: ["Caste Violence", "Family"], maturity: "A", mood: "Intense Rural Drama", year: 2019, rating: 8.4 },
    { id: 26, title: "Super Deluxe", language: "Tamil", genre: ["Drama", "Thriller"], tone: "Quirky", theme: ["Life", "Interconnected Stories"], maturity: "A", mood: "Quirky Multi-narrative Drama", year: 2019, rating: 8.3 },
    { id: 27, title: "Visaranai", language: "Tamil", genre: ["Crime", "Drama"], tone: "Brutal", theme: ["Police Brutality", "Justice"], maturity: "A", mood: "Brutal Crime Drama", year: 2015, rating: 8.6 },
    { id: 28, title: "Kaaka Muttai", language: "Tamil", genre: ["Drama", "Comedy"], tone: "Heartwarming", theme: ["Childhood", "Poverty", "Dreams"], maturity: "U", mood: "Heartwarming Children's Drama", year: 2014, rating: 8.4 },
    { id: 29, title: "Thani Oruvan", language: "Tamil", genre: ["Action", "Thriller"], tone: "Stylish", theme: ["Good vs Evil", "Intelligence"], maturity: "U/A", mood: "Stylish Action Thriller", year: 2015, rating: 8.3 },
    { id: 30, title: "Kadaikutty Singam", language: "Tamil", genre: ["Drama"], tone: "Rural", theme: ["Agriculture", "Family Values"], maturity: "U", mood: "Rural Family Drama", year: 2018, rating: 7.2 },
    { id: 31, title: "Pariyerum Perumal", language: "Tamil", genre: ["Drama"], tone: "Emotional", theme: ["Caste", "Education", "Love"], maturity: "U/A", mood: "Emotional Social Drama", year: 2018, rating: 8.7 },
    { id: 32, title: "Kolamavu Kokila", language: "Tamil", genre: ["Comedy", "Crime"], tone: "Dark Comedy", theme: ["Drugs", "Family"], maturity: "A", mood: "Dark Comedy Crime", year: 2018, rating: 7.4 },
    { id: 33, title: "Jigarthanda", language: "Tamil", genre: ["Comedy", "Action"], tone: "Stylish", theme: ["Cinema", "Gangsters"], maturity: "A", mood: "Stylish Meta-Cinema Comedy", year: 2014, rating: 8.2 },
    { id: 34, title: "Mersal", language: "Tamil", genre: ["Action", "Drama"], tone: "Commercial", theme: ["Healthcare", "Corruption"], maturity: "U/A", mood: "Commercial Action Drama", year: 2017, rating: 7.4 },

    // Telugu Films
    { id: 35, title: "Arjun Reddy", language: "Telugu", genre: ["Romance", "Drama"], tone: "Intense", theme: ["Love", "Self-Destruction"], maturity: "A", mood: "Intense Romance Drama", year: 2017, rating: 8.1 },
    { id: 36, title: "Pelli Choopulu", language: "Telugu", genre: ["Romance", "Comedy"], tone: "Light", theme: ["Modern Relationships", "Dreams"], maturity: "U", mood: "Light Romantic Comedy", year: 2016, rating: 8.2 },
    { id: 37, title: "Mahanati", language: "Telugu", genre: ["Biography", "Drama"], tone: "Nostalgic", theme: ["Cinema", "Life of Actor"], maturity: "U", mood: "Nostalgic Biographical Drama", year: 2018, rating: 8.6 },
    { id: 38, title: "Jersey", language: "Telugu", genre: ["Sports", "Drama"], tone: "Emotional", theme: ["Cricket", "Second Chances", "Family"], maturity: "U/A", mood: "Emotional Sports Drama", year: 2019, rating: 8.6 },
    { id: 39, title: "C/o Kancharapalem", language: "Telugu", genre: ["Romance", "Drama"], tone: "Realistic", theme: ["Love Across Ages", "Small Town"], maturity: "U/A", mood: "Realistic Multi-generational Romance", year: 2018, rating: 8.4 },
    { id: 40, title: "Geetha Govindam", language: "Telugu", genre: ["Romance", "Comedy"], tone: "Sweet", theme: ["Misunderstandings", "Love"], maturity: "U", mood: "Sweet Romantic Comedy", year: 2018, rating: 7.6 },
    { id: 41, title: "Khaidi No. 150", language: "Telugu", genre: ["Action", "Drama"], tone: "Commercial", theme: ["Farmer Issues", "Justice"], maturity: "U/A", mood: "Commercial Action Drama", year: 2017, rating: 6.9 },
    { id: 42, title: "Fidaa", language: "Telugu", genre: ["Romance", "Drama"], tone: "Rural", theme: ["Love", "Cultural Differences"], maturity: "U", mood: "Rural Romance Drama", year: 2017, rating: 7.7 },
    { id: 43, title: "Baahubali: The Beginning", language: "Telugu", genre: ["Action", "Drama", "Fantasy"], tone: "Epic", theme: ["Kingdom", "Revenge"], maturity: "U/A", mood: "Epic Fantasy Action", year: 2015, rating: 8.0 },
    { id: 44, title: "Premam", language: "Telugu", genre: ["Romance", "Comedy"], tone: "Youthful", theme: ["Love at Different Ages"], maturity: "U/A", mood: "Youthful Romance Comedy", year: 2016, rating: 8.2 },
    { id: 45, title: "Ninnu Kori", language: "Telugu", genre: ["Romance", "Drama"], tone: "Emotional", theme: ["Love Triangle", "Sacrifice"], maturity: "U/A", mood: "Emotional Romance Drama", year: 2017, rating: 7.6 },

    // Additional films to cross 50
    { id: 46, title: "Tumhari Sulu", language: "Hindi", genre: ["Comedy", "Drama"], tone: "Heartwarming", theme: ["Middle Class Dreams"], maturity: "U", mood: "Heartwarming Comedy", year: 2017, rating: 7.1 },
    { id: 47, title: "Ventilator", language: "Marathi", genre: ["Drama", "Comedy"], tone: "Emotional", theme: ["Family", "Relationships"], maturity: "U", mood: "Emotional Family Comedy", year: 2016, rating: 8.4 },
    { id: 48, title: "Ratsasan", language: "Tamil", genre: ["Thriller", "Crime"], tone: "Suspenseful", theme: ["Serial Killer", "Investigation"], maturity: "A", mood: "Suspenseful Crime Thriller", year: 2018, rating: 8.7 },
    { id: 49, title: "Maharshi", language: "Telugu", genre: ["Drama"], tone: "Inspirational", theme: ["Success", "Social Responsibility"], maturity: "U/A", mood: "Inspirational Social Drama", year: 2019, rating: 7.8 },
    { id: 50, title: "Anand", language: "Hindi", genre: ["Drama", "Comedy"], tone: "Uplifting", theme: ["Life", "Death", "Joy"], maturity: "U", mood: "Uplifting Life Drama", year: 1971, rating: 8.9 },
    { id: 51, title: "Kapoor & Sons", language: "Hindi", genre: ["Drama", "Comedy"], tone: "Realistic", theme: ["Family Dysfunction"], maturity: "U/A", mood: "Realistic Family Drama", year: 2016, rating: 7.7 },
    { id: 52, title: "Ugly", language: "Hindi", genre: ["Thriller", "Crime"], tone: "Dark", theme: ["Child Kidnapping", "Corruption"], maturity: "A", mood: "Dark Crime Thriller", year: 2013, rating: 7.9 }

];

// Metadata options for tagging
export const metadataOptions = {
  languages: ["Hindi", "Marathi", "Tamil", "Telugu", "Bengali", "Kannada", "Malayalam", "Gujarati", "Punjabi"],
  genres: ["Drama", "Comedy", "Action", "Romance", "Thriller", "Horror", "Crime", "Biography", "Sports", "Musical", "Adventure", "Fantasy", "Sci-Fi", "Documentary"],
  tones: ["Uplifting", "Dark", "Heartwarming", "Intense", "Light", "Serious", "Inspirational", "Nostalgic", "Realistic", "Tragic", "Humorous", "Melancholic", "Raw", "Passionate", "Gritty", "Brutal", "Emotional", "Commercial", "Satirical", "Epic"],
  themes: ["Family", "Love", "Friendship", "Justice", "Dreams", "Social Issues", "Caste", "Women's Rights", "Self-Discovery", "Independence", "Determination", "Deception", "Morality", "Good vs Evil", "Adventure", "Memory", "Time", "Police Brutality", "Childhood", "Poverty", "Music", "Art", "Cinema", "Cricket", "Second Chances", "Small Town", "Aging", "Respect", "Honor Killing", "Social Commentary", "Life", "Death"],
  maturities: ["U", "U/A", "A"],
  moods: [
    "Inspirational Sports Drama",
    "Dark Comedy Thriller", 
    "Uplifting Self-Discovery Comedy",
    "Serious Social Drama",
    "Inspirational Musical Drama",
    "Intense Romance Drama",
    "Realistic Legal Drama",
    "Tragic Family Drama",
    "Gritty Crime Thriller",
    "Nostalgic Romance Drama",
    "Intense Rural Drama",
    "Nostalgic Biographical Drama",
    "Emotional Sports Drama",
    "Realistic Multi-generational Romance",
    "Heartwarming Family Comedy",
    "Feel-Good Family Comedy",
    "Intense Social Thriller",
    "Adventure Buddy Comedy",
    "Horror Comedy",
    "Melancholic Social Drama"
  ]
};